[package]
name = "p2p-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.p2p]
path = ".."

[[bin]]
name = "reconcile_codec"
path = "fuzz_targets/reconcile_codec.rs"
test = false
doc = false
bench = false

[[bin]]
name = "reconcile_session"
path = "fuzz_targets/reconcile_session.rs"
test = false
doc = false
bench = false

[[bin]]
name = "reconcile_riblt"
path = "fuzz_targets/reconcile_riblt.rs"
test = false
doc = false
bench = false

[workspace]
